service:
  name: api-velog

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
#  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-2
  stage: dev
  environment:
    SECRET_KEY: ${env:SECRET_KEY}
    COCKROACHDB_HOST: ${env:COCKROACHDB_HOST}
    COCKROACHDB_PW: ${env:COCKROACHDB_PW}
    HASH_KEY: ${env:HASH_KEY}
    REDIS_HOST: ${env:REDIS_HOST}
    REDIS_PASS: ${env:REDIS_PASS}
    INTERNAL_KEY: ${env:INTERNAL_KEY}
    POSTGRES_HOST: ${env:POSTGRES_HOST}
    POSTGRES_USER: ${env:POSTGRES_USER}
    POSTGRES_PW: ${env:POSTGRES_PW}
    GITHUB_ID: ${env:GITHUB_ID}
    GITHUB_SECRET: ${env:GITHUB_SECRET}
    GOOGLE_ID: ${env:GOOGLE_ID}
    GOOGLE_SECRET: ${env:GOOGLE_SECRET}
    FACEBOOK_ID: ${env:FACEBOOK_ID}
    FACEBOOK_SECRET: ${env:FACEBOOK_SECRET}
    NODE_ENV: 'production'
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ec2:CreateNetworkInterface'
        - 'ec2:DescribeNetworkInterfaces'
        - 'ec2:DetachNetworkInterface'
        - 'ec2:DeleteNetworkInterface'
        - 'ses:SendEmail'
      Resource: '*'

functions:
  api:
    handler: src/api.handler
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: 'https://velog.io'
            headers:
              - Cookie
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
      - http:
          path: /{any+} # this matches any path, the token 'any' doesn't mean anything special
          method: ANY
          cors:
            origin: 'https://velog.io'
            headers:
              - Cookie
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
    vpc:
      securityGroupIds:
        - sg-5bc57830
        - sg-056b9986a73e2f766
      subnetIds:
        - subnet-91481ef9
        - subnet-4f59dc03
  checkImageFileSize:
    handler: src/schedules.checkImageFileSize
    events:
      - schedule: rate(5 minutes)

custom:
  apigwBinary:
    types: #list of mime-types
      - 'multipart/form-data'
      - 'application/x-www-form-urlencoded'
